Repository microsoft/gctoolkit, pull requests merged in 2021-08, with the labels that each got.

#15 Prepend `com.microsoft.` to all main modules
  core/api/src/main/java/module-info.java
  core/api/src/test/java/module-info.java
  core/parser/src/main/java/module-info.java
  core/parser/src/test/java/module-info.java
  core/vertx/src/main/java/module-info.java
  core/vertx/src/test/java/module-info.java
  sample/src/main/java/module-info.java
Labels: enhancement

#17 Compile version information into Java modules
  pom.xml
Labels: enhancement

#23 Updated message to GCToolKit is a set of libraries for analyzing Hotspot
  README.md
Labels: documentation, enhancement

#27 Update Docs to improve understanding for first time contributors
  .gitignore
  CONTRIBUTING.md
  README.md
  clean.sh
  sample/README.md
  sample/pom.xml
  sample/src/main/java/com/microsoft/gctoolkit/sample/Main.java
Labels: documentation, enhancement

#33 added checkstyle and spotbugs plugin
  pom.xml
Labels: enhancement

#39 Added comparable interface for DateTimeStamp and its implementation.
  core/api/src/main/java/com/microsoft/gctoolkit/time/DateTimeStamp.java
  core/api/src/test/java/com/microsoft/gctoolkit/test/time/DateTimeStampTest.java
Labels: enhancement

#53 Prepend `com.microsoft.` to sample's module name
  sample/README.md
  sample/pom.xml
  sample/src/main/java/module-info.java
Labels: enhancement

#50 Added handling for NAN in add method of DateTimeStamp
  core/api/src/main/java/com/microsoft/gctoolkit/time/DateTimeStamp.java
  core/api/src/test/java/com/microsoft/gctoolkit/test/time/DateTimeStampTest.java
Labels: bug

#59 Lots of small fixes from linters and improve docs
  CONTRIBUTING.md
  README.md
  sample/README.md
Labels: documentation, enhancement

#40 add script to run the sample
  sample/sample.sh
  sample/src/main/java/com/microsoft/gctoolkit/sample/aggregation/HeapOccupancyAfterCollectionSummary.java
Labels: enhancement

#60 Three small improvements
  core/api/src/main/java/com/microsoft/gctoolkit/GCToolKit.java
  core/api/src/main/java/com/microsoft/gctoolkit/aggregator/JVMEventDispatcher.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/GCCauses.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/GarbageCollectionTypes.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/LabelledGCEventType.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1FullGC.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1Trap.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1Young.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/jvm/SurvivorRecord.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/ZGCConcurrentPhases.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/ZGCPauseTypes.java
  core/api/src/main/java/com/microsoft/gctoolkit/io/FileDataSourceMetaData.java
  core/api/src/main/java/com/microsoft/gctoolkit/io/RotatingGCLogFile.java
  core/api/src/main/java/com/microsoft/gctoolkit/time/DateTimeStamp.java
  core/api/src/main/java/com/microsoft/gctoolkit/util/concurrent/StartingGun.java
  core/api/src/main/java/module-info.java
  core/api/src/test/java/com/microsoft/gctoolkit/test/util/concurrent/StartingGunTest.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/G1GCForwardReference.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GenerationalForwardReference.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GenerationalHeapParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/JVMEventParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/PreUnifiedG1GCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/SafepointParseRule.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/UnifiedG1GCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/UnifiedGenerationalParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/collection/MRUQueue.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/collection/RuleSet.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/JVMFlags.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/CommonTestHelper.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ConcurrentMarkSweepParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/G1GCParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/G1GCUnifiedParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ParallelParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ShenandoahParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/TestLogFile.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/UnifiedGenerationalParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ZGCParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/collection/MRUQueueTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/patterns/CMSTenuredParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/patterns/G1GCPatternsTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/patterns/GenerationalParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/ParserTest.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/GCToolkitVertx.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/JVMEventSource.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/aggregator/AggregatorVerticle.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/DefaultJavaVirtualMachine.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/GCToolkitVertxParameters.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/LogFileParser.java
  core/vertx/src/test/java/com/microsoft/gctoolkit/vertx/test/io/TestLogFile.java
  sample/src/main/java/com/microsoft/gctoolkit/sample/aggregation/HeapOccupancyAfterCollectionSummary.java
Labels: enhancement

#61 Clean code
  core/api/src/test/java/com/microsoft/gctoolkit/test/collections/XYDataSetTest.java
  core/api/src/test/java/com/microsoft/gctoolkit/test/io/RotatingGarbageCollectionLogFileTest.java
  sample/src/main/java/com/microsoft/gctoolkit/sample/Main.java
Labels: enhancement

#62 Fix typos suggested by IntelliJ
  CONTRIBUTING.md
  README.md
  core/pom.xml
  pom.xml
Labels: bug, documentation

#65 Cleanup
  core/api/src/main/java/com/microsoft/gctoolkit/GCToolKit.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/GCEvent.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/MemoryPoolSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/RegionSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/UnifiedCountSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/UnifiedStatisticalSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1GCPauseEvent.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1Trap.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/jvm/ApplicationStoppedTime.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/jvm/ClassspaceSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/jvm/Safepoint.java
  core/api/src/main/java/com/microsoft/gctoolkit/io/GarbageCollectionLogFileSegment.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/G1GCForwardReference.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GCLogTrace.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GenerationalHeapParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/JHiccupTrace.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/PreUnifiedG1GCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/ShenandoahParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/UnifiedG1GCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/ZGCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/collection/MRUQueue.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/collection/RuleSet.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/CommandLineFlag.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/GarbageCollectorFlag.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/PreUnifiedJVMConfiguration.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/UnifiedJVMConfiguration.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/vmops/SafepointTrace.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ConcurrentMarkSweepParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ConcurrentMarkSweepPhaseParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/IncrementialConcurrentMarkSweepParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ParallelParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ShenandoahParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/TestLogFile.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/UnifiedGenerationalParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/CMSDefNewLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/CMSLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/CMSParNewLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/CommandLineFlagsLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/G1JVMConfigurationTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/ParallelJVMConfigurationTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/SerialDefNewLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/ShenandoahLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/VerboseLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/ZGCLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/jvm/DecoratorsTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/CMSParNewParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/ICMSParNewParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/ParallelCollectorParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/ParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/PreunifiedG1GCParserTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/unittests/UnifiedG1GCParserTest.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/JVMEventSource.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/aggregator/AggregatorVerticle.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/JVMEventMailbox.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/LogFileParser.java
  core/vertx/src/test/java/com/microsoft/gctoolkit/vertx/test/io/GarbageCollectionEventSourceTest.java
  core/vertx/src/test/java/com/microsoft/gctoolkit/vertx/test/io/TestLogFile.java
Labels: enhancement
