Repository microsoft/gctoolkit, pull requests merged in 2021-09, with the labels that each got.

#66 Add Maven Wrapper for better onboarding
  .github/workflows/maven.yml
  .github/workflows/publish.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: enhancement

#69 reproducible builds
  pom.xml
Labels: enhancement

#71 Update docs for mvnw
  CONTRIBUTING.md
  sample/README.md
Labels: documentation, enhancement

#86 Avoid compiler warnings by removing unused imports
  core/api/src/main/java/com/microsoft/gctoolkit/event/GCCauses.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/GarbageCollectionTypes.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1Young.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/ZGCConcurrentPhases.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/ZGCPauseTypes.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/LogFileParser.java
Labels: bug

#70 Removes auto loading aggregators. Requires API call
  core/api/src/main/java/com/microsoft/gctoolkit/GCToolKit.java
  core/api/src/main/java/com/microsoft/gctoolkit/jvm/JavaVirtualMachine.java
  core/vertx/src/main/java/com/microsoft/gctoolkit/vertx/jvm/DefaultJavaVirtualMachine.java
  sample/src/main/java/com/microsoft/gctoolkit/sample/Main.java
Labels: enhancement, question

#91 downgraded maven.license-plugin.version to 1.20
  pom.xml
Labels: bug

#92 suppress unchecked cast warnings
  core/api/src/main/java/com/microsoft/gctoolkit/aggregator/JVMEventDispatcher.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/collection/MRUQueue.java
Labels: enhancement

#94 fix issue #93 with UnifiedGenerationalHeapParser
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/UnifiedGenerationalParser.java
Labels: bug

#90 VS Code DevContainer Config and TestData Download with Maven
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .mvn/jvm.config
  pom.xml
Labels: enhancement

#99 Sorted the modifiers of fields according to best practices
  core/api/src/main/java/com/microsoft/gctoolkit/aggregator/Aggregator.java
  core/api/src/main/java/com/microsoft/gctoolkit/collections/XYDataSet.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/GCCauses.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/StatisticalSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1GCConcurrentEvent.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/g1gc/G1GCEvent.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/generational/CMSConcurrentEvent.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/generational/CMSPauseEvent.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/OccupancySummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/ReclaimSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/event/zgc/ZGCMemoryPoolSummary.java
  core/api/src/main/java/com/microsoft/gctoolkit/io/FileDataSourceMetaData.java
  core/api/src/main/java/com/microsoft/gctoolkit/io/RotatingGCLogFile.java
  core/api/src/main/java/com/microsoft/gctoolkit/io/SingleGCLogFile.java
  core/api/src/test/java/com/microsoft/gctoolkit/test/time/DateTimeStampTest.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/CMSTenuredPoolParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/ForwardReference.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/G1GCForwardReference.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/G1GCPatterns.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GCLogParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GCParseRule.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/GenerationalHeapParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/JVMEventParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/ParNewSerial.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/PreUnifiedG1GCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/SafepointParseRule.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/ShenandoahParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/UnifiedG1GCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/ZGCParser.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/Decorators.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/jvm/PreUnifiedJVMConfiguration.java
  core/parser/src/main/java/com/microsoft/gctoolkit/parser/unified/UnifiedLoggingCMSPatterns.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/ShenandoahParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/TestLogFile.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/UnifiedGenerationalParserRulesTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/diary/CommandLineFlagsLogDiaryTest.java
  core/parser/src/test/java/com/microsoft/gctoolkit/parser/test/jvm/DecoratorsTest.java
  core/vertx/src/test/java/com/microsoft/gctoolkit/vertx/test/io/TestLogFile.java
Labels: enhancement

#76 Unit test to demonstrate that the DateTimeStamp compareTo function is…
  core/api/src/test/java/com/microsoft/gctoolkit/test/time/DateTimeStampTest.java
Labels: enhancement

#97 Xy data set refactor
  core/api/src/main/java/module-info.java
  sample/pom.xml
  sample/src/main/java/com/microsoft/gctoolkit/sample/aggregation/HeapOccupancyAfterCollectionSummary.java
  sample/src/main/java/com/microsoft/gctoolkit/sample/collections/XYDataSet.java
  sample/src/main/java/module-info.java
  sample/src/test/java/com/microsoft/gctoolkit/sample/test/collections/XYDataSetTest.java
  sample/src/test/java/module-info.java
Labels: enhancement

#102 Pom cleanup: Added values for name,descrption,url tag
  api/pom.xml
  core/pom.xml
  gclogs/pom.xml
  parser/pom.xml
  sample/pom.xml
  vertx/pom.xml
Labels: enhancement
